In [11]:
import numpy as np
A = np.array([1,2,3])
B = np.array([2,1,2])
result = np.inner(A,B)
print(result)

10


In [12]:
X = np.array([[2,3],[1,2]])
Y = np.array([[1,4],[1,2]])
result = np.inner(X,Y)
print(result)

[[14  8]
 [ 9  5]]


In [10]:
import numpy as np
A = np.array([1,2,3])
B = np.array([2,1,2])
result = np.outer(A,B)
print(result)

[[2 1 2]
 [4 2 4]
 [6 3 6]]


In [7]:
X = np.array([[2,3],[1,2]])
Y = np.array([[1,4],[1,2]])
result = np.outer(X,Y)
print(result)

[[ 2  8  2  4]
 [ 3 12  3  6]
 [ 1  4  1  2]
 [ 2  8  2  4]]


In [15]:
A = np.array([[3,2],[3,4]])
det_A = np.linalg.det(A)

In [16]:
det_A 

6.0

In [23]:
B = np.array([[1,2,3],[1,3,4],[1,5,3]])
det_B = np.linalg.det(B)

In [24]:
det_B

-3.0000000000000004

In [25]:
A = np.array([[1,4],[1,2]])
b = np.array([4,5])
x = np.linalg.solve(A,b)
print(x)

[ 6.  -0.5]


In [26]:
A = np.array([[1,2],[1,3]])
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 3. -2.]
 [-1.  1.]]
