In [1]:
!pip install pandas

     ---------------------------------------- 11.1/11.1 MB 8.8 MB/s eta 0:00:00
     ---------------------------------------- 13.0/13.0 MB 9.8 MB/s eta 0:00:00
     ------------------------------------- 509.2/509.2 kB 10.6 MB/s eta 0:00:00
     ------------------------------------- 347.8/347.8 kB 22.5 MB/s eta 0:00:00



[notice] A new release of pip available: 22.3 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [52]:
import pandas as pd

In [53]:
calories = [200,300,250,350]

In [54]:
data = pd.Series(calories,index=["day1","day2","day3","day4"])

In [55]:
print(data["day3"])

250


In [56]:
data

day1    200
day2    300
day3    250
day4    350
dtype: int64

In [57]:
person = pd.DataFrame({"id":[1,2,3,4],"name":["Abin","Aju","Eby","Jin"],"user_id":[101,102,103,104]},index=[100,200,300,400])

In [58]:
person

id  name  user_id
100   1  Abin      101
200   2   Aju      102
300   3   Eby      103
400   4   Jin      104

In [59]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [60]:
print(np.dot(a,b))

32


In [61]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [62]:
print(A+B)

[[ 6  8]
 [10 12]]


In [63]:
print(np.add(A,B))

[[ 6  8]
 [10 12]]


In [64]:
A = np.array([[2, 1], [3, 2]])
b = np.array([5, 8])

In [65]:
result=np.linalg.solve(A,b)

In [66]:
result

array([2., 1.])

In [67]:
A = np.array([[4, 7], [2, 6]])

In [68]:
print(np.linalg.det(A))

10.000000000000002


In [69]:
B = np.array([[1,2,3],[3,4,6],[2,3,4]])

In [70]:
print(np.linalg.det(B))

1.0000000000000002


In [71]:
x = np.array([0,1,2,3,4,5,6,7,8,9])

In [72]:
y = np.array([0,1,2,3,4,5,6,7,8,9, 8,3])

In [73]:
print(y.reshape(3,4))

[[0 1 2 3]
 [4 5 6 7]
 [8 9 8 3]]


In [74]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [75]:
print(a.shape)

(2, 3)


In [76]:
print(a.size)

6


In [77]:
print(a.dtype)

int64


In [78]:
import pandas as pd

In [79]:
df = pd.DataFrame({"name":["Akhil","Manu","John"],"age":[30,45,60]})

In [80]:
df

name  age
0  Akhil   30
1   Manu   45
2   John   60

In [81]:
df.to_csv("person.csv", index=False)

In [82]:
data = pd.read_csv("person.csv")

In [83]:
data

name  age
0  Akhil   30
1   Manu   45
2   John   60

In [84]:
df.head()

name  age
0  Akhil   30
1   Manu   45
2   John   60

In [85]:
df.tail()

name  age
0  Akhil   30
1   Manu   45
2   John   60

In [86]:
df = pd.read_csv("sales_data.csv")

In [87]:
df.head()

Product_ID   Sale_Date Sales_Rep Region  Sales_Amount  Quantity_Sold  \
0        1052  2023-02-03       Bob  North       5053.97             18   
1        1093  2023-04-21       Bob   West       4384.02             17   
2        1015  2023-09-21     David  South       4631.23             30   
3        1072  2023-08-24       Bob  South       2167.94             39   
4        1061  2023-03-24   Charlie   East       3750.20             13   

  Product_Category  Unit_Cost  Unit_Price Customer_Type  Discount  \
0        Furniture     152.75      267.22     Returning      0.09   
1        Furniture    3816.39     4209.44     Returning      0.11   
2             Food     261.56      371.40     Returning      0.20   
3         Clothing    4330.03     4467.75           New      0.02   
4      Electronics     637.37      692.71           New      0.08   

  Payment_Method Sales_Channel Region_and_Sales_Rep  
0           Cash        Online            North-Bob  
1           Cash        Retail             West-Bob  
2  Bank Transfer        Retail          South-David  
3    Credit Card        Retail            South-Bob  
4    Credit Card        Online         East-Charlie

In [88]:
df.tail()

Product_ID   Sale_Date Sales_Rep Region  Sales_Amount  Quantity_Sold  \
995        1010  2023-04-15   Charlie  North       4733.88              4   
996        1067  2023-09-07       Bob  North       4716.36             37   
997        1018  2023-04-27     David  South       7629.70             17   
998        1100  2023-12-20     David   West       1629.47             39   
999        1086  2023-08-16     Alice   East       4923.93             48   

    Product_Category  Unit_Cost  Unit_Price Customer_Type  Discount  \
995             Food    4943.03     5442.15     Returning      0.29   
996         Clothing    1754.32     1856.40           New      0.21   
997         Clothing     355.72      438.27     Returning      0.06   
998      Electronics    3685.03     3743.39           New      0.01   
999             Food    2632.58     2926.68     Returning      0.14   

    Payment_Method Sales_Channel Region_and_Sales_Rep  
995           Cash        Online        North-Charlie  
996  Bank Transfer        Retail            North-Bob  
997  Bank Transfer        Online          South-David  
998  Bank Transfer        Online           West-David  
999           Cash        Online           East-Alice

In [89]:
df.columns

Index(['Product_ID', 'Sale_Date', 'Sales_Rep', 'Region', 'Sales_Amount',
       'Quantity_Sold', 'Product_Category', 'Unit_Cost', 'Unit_Price',
       'Customer_Type', 'Discount', 'Payment_Method', 'Sales_Channel',
       'Region_and_Sales_Rep'],
      dtype='object')

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Product_ID            1000 non-null   int64  
 1   Sale_Date             1000 non-null   object 
 2   Sales_Rep             1000 non-null   object 
 3   Region                1000 non-null   object 
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64  
 6   Product_Category      1000 non-null   object 
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   object 
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   object 
 12  Sales_Channel         1000 non-null   object 
 13  Region_and_Sales_Rep  1000 non-null   object 
dtypes: float64(4), int64(2), object(8)
memory usage: 109.5+ KB


In [91]:
df.shape

(1000, 14)

In [92]:
df.describe()

Product_ID  Sales_Amount  Quantity_Sold    Unit_Cost   Unit_Price  \
count  1000.000000   1000.000000    1000.000000  1000.000000  1000.000000   
mean   1050.128000   5019.265230      25.355000  2475.304550  2728.440120   
std      29.573505   2846.790126      14.159006  1417.872546  1419.399839   
min    1001.000000    100.120000       1.000000    60.280000   167.120000   
25%    1024.000000   2550.297500      13.000000  1238.380000  1509.085000   
50%    1051.000000   5019.300000      25.000000  2467.235000  2696.400000   
75%    1075.000000   7507.445000      38.000000  3702.865000  3957.970000   
max    1100.000000   9989.040000      49.000000  4995.300000  5442.150000   

         Discount  
count  1000.00000  
mean      0.15239  
std       0.08720  
min       0.00000  
25%       0.08000  
50%       0.15000  
75%       0.23000  
max       0.30000

In [93]:
student={"name":["Abin","Ajas","Basil","Kevin"],"marks":[45,23,56,67]}

In [94]:
df = pd.DataFrame(student)

In [95]:
df.to_csv("student.csv",index=False)

In [96]:
df

name  marks
0   Abin     45
1   Ajas     23
2  Basil     56
3  Kevin     67

In [97]:
data = pd.read_csv("sales_data.csv")

In [98]:
data.shape

(1000, 14)

In [99]:
data.columns

Index(['Product_ID', 'Sale_Date', 'Sales_Rep', 'Region', 'Sales_Amount',
       'Quantity_Sold', 'Product_Category', 'Unit_Cost', 'Unit_Price',
       'Customer_Type', 'Discount', 'Payment_Method', 'Sales_Channel',
       'Region_and_Sales_Rep'],
      dtype='object')

In [100]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Product_ID            1000 non-null   int64  
 1   Sale_Date             1000 non-null   object 
 2   Sales_Rep             1000 non-null   object 
 3   Region                1000 non-null   object 
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64  
 6   Product_Category      1000 non-null   object 
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   object 
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   object 
 12  Sales_Channel         1000 non-null   object 
 13  Region_and_Sales_Rep  1000 non-null   object 
dtypes: float64(4), int64(2), object(8)
memory usage: 109.5+ KB


In [101]:
import pandas as pd

In [102]:
sales_data = pd.read_csv("sales_data.csv")

In [103]:
sales_data.head()

Product_ID   Sale_Date Sales_Rep Region  Sales_Amount  Quantity_Sold  \
0        1052  2023-02-03       Bob  North       5053.97             18   
1        1093  2023-04-21       Bob   West       4384.02             17   
2        1015  2023-09-21     David  South       4631.23             30   
3        1072  2023-08-24       Bob  South       2167.94             39   
4        1061  2023-03-24   Charlie   East       3750.20             13   

  Product_Category  Unit_Cost  Unit_Price Customer_Type  Discount  \
0        Furniture     152.75      267.22     Returning      0.09   
1        Furniture    3816.39     4209.44     Returning      0.11   
2             Food     261.56      371.40     Returning      0.20   
3         Clothing    4330.03     4467.75           New      0.02   
4      Electronics     637.37      692.71           New      0.08   

  Payment_Method Sales_Channel Region_and_Sales_Rep  
0           Cash        Online            North-Bob  
1           Cash        Retail             West-Bob  
2  Bank Transfer        Retail          South-David  
3    Credit Card        Retail            South-Bob  
4    Credit Card        Online         East-Charlie

In [104]:
sales_data.tail()

Product_ID   Sale_Date Sales_Rep Region  Sales_Amount  Quantity_Sold  \
995        1010  2023-04-15   Charlie  North       4733.88              4   
996        1067  2023-09-07       Bob  North       4716.36             37   
997        1018  2023-04-27     David  South       7629.70             17   
998        1100  2023-12-20     David   West       1629.47             39   
999        1086  2023-08-16     Alice   East       4923.93             48   

    Product_Category  Unit_Cost  Unit_Price Customer_Type  Discount  \
995             Food    4943.03     5442.15     Returning      0.29   
996         Clothing    1754.32     1856.40           New      0.21   
997         Clothing     355.72      438.27     Returning      0.06   
998      Electronics    3685.03     3743.39           New      0.01   
999             Food    2632.58     2926.68     Returning      0.14   

    Payment_Method Sales_Channel Region_and_Sales_Rep  
995           Cash        Online        North-Charlie  
996  Bank Transfer        Retail            North-Bob  
997  Bank Transfer        Online          South-David  
998  Bank Transfer        Online           West-David  
999           Cash        Online           East-Alice

In [105]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Product_ID            1000 non-null   int64  
 1   Sale_Date             1000 non-null   object 
 2   Sales_Rep             1000 non-null   object 
 3   Region                1000 non-null   object 
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64  
 6   Product_Category      1000 non-null   object 
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   object 
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   object 
 12  Sales_Channel         1000 non-null   object 
 13  Region_and_Sales_Rep  1000 non-null   object 
dtypes: float64(4), int64(2), object(8)
memory usage: 109.5+ KB


In [106]:
sales_data.describe()

Product_ID  Sales_Amount  Quantity_Sold    Unit_Cost   Unit_Price  \
count  1000.000000   1000.000000    1000.000000  1000.000000  1000.000000   
mean   1050.128000   5019.265230      25.355000  2475.304550  2728.440120   
std      29.573505   2846.790126      14.159006  1417.872546  1419.399839   
min    1001.000000    100.120000       1.000000    60.280000   167.120000   
25%    1024.000000   2550.297500      13.000000  1238.380000  1509.085000   
50%    1051.000000   5019.300000      25.000000  2467.235000  2696.400000   
75%    1075.000000   7507.445000      38.000000  3702.865000  3957.970000   
max    1100.000000   9989.040000      49.000000  4995.300000  5442.150000   

         Discount  
count  1000.00000  
mean      0.15239  
std       0.08720  
min       0.00000  
25%       0.08000  
50%       0.15000  
75%       0.23000  
max       0.30000

In [107]:
sales_data.shape

(1000, 14)

In [108]:
sales_data.columns

Index(['Product_ID', 'Sale_Date', 'Sales_Rep', 'Region', 'Sales_Amount',
       'Quantity_Sold', 'Product_Category', 'Unit_Cost', 'Unit_Price',
       'Customer_Type', 'Discount', 'Payment_Method', 'Sales_Channel',
       'Region_and_Sales_Rep'],
      dtype='object')

In [109]:
student_data = {"name":["Ajith","Basil","Joseph"], "age":[34,65,56]}

In [110]:
stud_data = pd.DataFrame(student_data)

In [111]:
stud_data

name  age
0   Ajith   34
1   Basil   65
2  Joseph   56

In [112]:
stud_data.dtypes

name    object
age      int64
dtype: object

In [113]:
stud_data.columns

Index(['name', 'age'], dtype='object')

In [114]:
stud_data.describe()

age
count   3.000000
mean   51.666667
std    15.947832
min    34.000000
25%    45.000000
50%    56.000000
75%    60.500000
max    65.000000

In [115]:
stud_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes


In [116]:
stud_data.dtypes

name    object
age      int64
dtype: object

In [117]:
stud_data.shape

(3, 2)

In [118]:
stud_data.head()

name  age
0   Ajith   34
1   Basil   65
2  Joseph   56

In [119]:
stud_data.columns

Index(['name', 'age'], dtype='object')

In [120]:
df = pd.DataFrame(student_data)

In [121]:
df

name  age
0   Ajith   34
1   Basil   65
2  Joseph   56

In [122]:
df["name"]

0     Ajith
1     Basil
2    Joseph
Name: name, dtype: object

In [123]:
df["age"]

0    34
1    65
2    56
Name: age, dtype: int64

In [124]:
series = pd.Series([24,54,23,56])

In [125]:
series

0    24
1    54
2    23
3    56
dtype: int64

In [126]:
series[2]

np.int64(23)

In [127]:
df[["name","age"]]

name  age
0   Ajith   34
1   Basil   65
2  Joseph   56

In [128]:
df.iloc[0]

name    Ajith
age        34
Name: 0, dtype: object

In [129]:
df[1:3]

name  age
1   Basil   65
2  Joseph   56

In [130]:
df[(df["age"] > 50)]

name  age
1   Basil   65
2  Joseph   56

In [131]:
df[(df["age"] < 50)]

name  age
0  Ajith   34

In [132]:
df["Place"] = ["Kochi","Kottayam","Thrissur"]

In [133]:
df

name  age     Place
0   Ajith   34     Kochi
1   Basil   65  Kottayam
2  Joseph   56  Thrissur

In [134]:
df.loc[0,"age"] = 40

In [135]:
df

name  age     Place
0   Ajith   40     Kochi
1   Basil   65  Kottayam
2  Joseph   56  Thrissur

In [136]:
df.rename(columns={'name':'name', 'Ages': 'Age'}, inplace=True)

In [137]:
df

name  age     Place
0   Ajith   40     Kochi
1   Basil   65  Kottayam
2  Joseph   56  Thrissur

In [138]:
df.drop('Place',axis=1, inplace=True)

In [139]:
df

name  age
0   Ajith   40
1   Basil   65
2  Joseph   56

In [140]:
df.drop(index=2, axis=0, inplace=True)

In [141]:
df

name  age
0  Ajith   40
1  Basil   65